### ISSUE TITLE
Right click with day view and scheduler

### ISSUE THREAD

**Issue by jlannoy** [mherrmann/fullcalendar-rightclick#20]
Hello.

I was unable to use fullcalendar-rightclick.js with the day and scheduler views. The problem comes from this line (81) :

```javascript
// FullCalendar >= 3.5.0:
cell = hit.component.getCellRange(hit.row, hit.col);
```

On these views the hit.row is undefined. It seems legit as there is only one day displayed. 

But I was able to fix it this ways :

```javascript
// FullCalendar >= 3.5.0:
// Update for day view
if(hit.row) {
	cell = hit.component.getCellRange(hit.row, hit.col);
} else {
    	var componentFootprint = hit.component.getSafeHitFootprint(hit);
	if (componentFootprint) {
		var dateProfile = that.calendar.footprintToDateProfile(componentFootprint);
		cell = { start: dateProfile.start, end: dateProfile.end };
	}
}
```

It uses the same base as the dayClick callback used by fullcalendar to get the exact instant target (hour/minutes included). As I'm not sure the _hit.row_ is the right way to detect it, nor am I able to provide a unit test, I didn't send a pull request. ;)

**Comment by mherrmann** [comment]
Do you think this could be caused by your recent PR @duckbrain?

**Comment by duckbrain** [comment]
@jlannoy What version of FullCalendar and the scheduler plugin are you using? I'm assuming >= 3.5.0, but if not, there's a problem with version detection. 

@mherrmann Almost certainly. I haven't reproduced it yet in testing, but I'm not going to have a lot of time to look into it. Hopefully it's a quick fix.

**Comment by mherrmann** [comment]
@duckbrain okay thanks! Looking forward to your findings.

**Comment by duckbrain** [comment]
Okay, I reproduced the issue. Happens in >= 3.5.0. Only happens in the `agendaDay` and `agendaWeek` views (and probably the scheduler plugin, but I haven't tested for that). @jlannoy's fix seems to do it. PR to come.

```
TypeError: Cannot read property 'clone' of undefined
    at TimeGrid.DayTableMixin.getCellDate (https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.0/fullcalendar.js:6702:62)
    at TimeGrid.DayTableMixin.getCellRange (https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.0/fullcalendar.js:6706:26)
    at HTMLDivElement.<anonymous> (file:///home/jonathan/src/github.com/ec2-software/fullcalendar-rightclick/fullcalendar-rightclick.js:81:30)
    at HTMLDivElement.dispatch (https://code.jquery.com/jquery-2.1.3.js:4430:9)
    at HTMLDivElement.elemData.handle (https://code.jquery.com/jquery-2.1.3.js:4116:28)
    at Object.trigger (https://code.jquery.com/jquery-2.1.3.js:4345:12)
    at HTMLTableCellElement.<anonymous> (https://code.jquery.com/jquery-2.1.3.js:4896:17)
    at Function.each (https://code.jquery.com/jquery-2.1.3.js:374:23)
    at jQuery.fn.init.each (https://code.jquery.com/jquery-2.1.3.js:139:17)
    at jQuery.fn.init.trigger (https://code.jquery.com/jquery-2.1.3.js:4895:15)
```

**Comment by jlannoy** [comment]
Thank you guys!
